language: node_js
node_js:
  - lts/*

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      skip_cleanup: true
      script:
        # Skip script until version 1.0.0
        # - npm run semantic-release
