language: node_js
node_js:
  - node

script:
  - npm run build
  - npm run lint
  - npm run docs
  - npm run test:coveralls

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run release
  on:
    branch: master
