language: node_js
node_js:
  - lts/*

script:
  - npm run build
  - npm run lint
  - npm run docs

deploy:
  on:
    branch: master
    node: 'lts/*'
  provider: script
  skip_cleanup: true
  script:
    # Skip script until version 1.0.0
    # - npm run release
