language: node_js
node_js:
  - node

script:
  - npm run build
  - npm run lint
  - npm run docs
  - npm run test:coveralls

deploy:
  provider: script
  skip_cleanup: true
  script:
    # Skip script until version 1.0.0
    #- npm run release
    - echo "placeholder deploy"
  on:
    branch: master
